// <auto-generated />
using LinearRegression.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace LinearRegression.Database.Migrations
{
    [DbContext(typeof(LinearRegressionDbContext))]
    [Migration("20180323144900_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("LinearRegression.Database.Model.Analysis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreationDate");

                    b.Property<string>("Descrioption");

                    b.Property<string>("Title");

                    b.Property<string>("XData");

                    b.Property<string>("XMeaning");

                    b.Property<string>("YData");

                    b.Property<string>("YMeaning");

                    b.HasKey("Id");

                    b.ToTable("AnalysisSet");
                });
#pragma warning restore 612, 618
        }
    }
}
