// <auto-generated />
using LinearRegression.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace LinearRegression.Database.Migrations
{
    [DbContext(typeof(LinearRegressionDbContext))]
    partial class LinearRegressionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("LinearRegression.Database.Model.AnalysisData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AnalysisInformationId");

                    b.Property<string>("XData");

                    b.Property<string>("XMeaning");

                    b.Property<string>("YData");

                    b.Property<string>("YMeaning");

                    b.HasKey("Id");

                    b.ToTable("AnalysisDataSet");
                });

            modelBuilder.Entity("LinearRegression.Database.Model.AnalysisInformation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AnalysisDataId");

                    b.Property<string>("CreationDate");

                    b.Property<string>("Descrioption");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("AnalysisInformationSet");
                });
#pragma warning restore 612, 618
        }
    }
}
