language: csharp
solution: LinearRegression.sln
install:
  - nuget restore LinearRegression.sln
  - nuget install NUnit.Runners -Version 3.10.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=LinearRegression.sln
  - mono ./testrunner/NUnit.Runners.3.10.1/tools/nunit-console.exe ./LinearRegression.Tests/bin/Release/LinearRegression.Tests.dll