language: csharp
solution: solution-name.sln
install:
  - nuget restore solution-name.sln
  - nuget install NUnit.Runners -Version 3.10.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=LinearRegression.sln
  - mono ./testrunner/NUnit.Runners.3.10.1/tools/nunit-console.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll