language: csharp
solution: LinearRegression.sln
install:
  - nuget restore LinearRegression.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=LinearRegression.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./LinearRegression.Tests/bin/Release/LinearRegression.Tests.dll