language: csharp
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore LinearRegression.sln
after_script:
  - nunit-console LinearRegression.Tests/bin/Release/LinearRegression.Tests.dll